apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deployment
  namespace: abc-ns
  labels:
    app: abctech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abctech
  template:
    metadata:
      labels:
        app: abctech
    spec:
      containers:
      - name: abctech-container
        image: eprasa4/abctechnologies:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"